const ordersList = [
  {
    id: 1,
    customer: 'John Doe',
    image: './wig2.jpg',
    status: 'Processing',
    value: 150.0,
  },
  {
    id: 2,
    customer: 'Jane Smith',
    image: './wig3.jpg',
    status: 'Shipped',
    value: 75.5,
  },
  {
    id: 3,
    customer: 'Bob Johnson',
    image: './wig4.jpg',
    status: 'Delivered',
    value: 200.25,
  },
  {
    id: 4,
    customer: 'Alice Brown',
    image: './wig2.jpg',
    status: 'Pending',
    value: 120.75,
  },
  {
    id: 5,
    customer: 'Eva White',
    image: './wig5.jpg',
    status: 'Processing',
    value: 90.0,
  },
  {
    id: 6,
    customer: 'Mike Green',
    image: './wig2.jpg',
    status: 'Shipped',
    value: 180.5,
  },
  {
    id: 7,
    customer: 'Sophie Black',
    image: './wig2.jpg',
    status: 'Delivered',
    value: 60.25,
  },
  {
    id: 8,
    customer: 'David Gray',
    image: './wig2.jpg',
    status: 'Pending',
    value: 300.0,
  },
  {
    id: 9,
    customer: 'Linda Taylor',
    image: './wig2.jpg',
    status: 'Processing',
    value: 45.75,
  },
  {
    id: 10,
    customer: 'Chris Anderson',
    image: './wig2.jpg',
    status: 'Shipped',
    value: 150.2,
  },
  {
    id: 11,
    customer: 'Emily Wilson',
    image: './wig2.jpg',
    status: 'Delivered',
    value: 80.0,
  },
  {
    id: 12,
    customer: 'Tom Baker',
    image: './wig2.jpg',
    status: 'Pending',
    value: 130.5,
  },
  {
    id: 13,
    customer: 'Samantha Carter',
    image: './wig2.jpg',
    status: 'Processing',
    value: 210.75,
  },
  {
    id: 14,
    customer: 'Harry Martin',
    image: './wig2.jpg',
    status: 'Shipped',
    value: 95.3,
  },
  {
    id: 15,
    customer: 'Olivia Davis',
    image: './wig2.jpg',
    status: 'Delivered',
    value: 175.0,
  },
  {
    id: 16,
    customer: 'Peter Turner',
    image: './wig2.jpg',
    status: 'Pending',
    value: 110.25,
  },
  {
    id: 17,
    customer: 'Mia Clark',
    image: './wig2.jpg',
    status: 'Processing',
    value: 220.5,
  },
  {
    id: 18,
    customer: 'Alex Harris',
    image: './wig2.jpg',
    status: 'Shipped',
    value: 70.8,
  },
  {
    id: 19,
    customer: 'Daniel Miller',
    image: './wig2.jpg',
    status: 'Delivered',
    value: 155.25,
  },
  {
    id: 20,
    customer: 'Grace Wilson',
    image: './wig2.jpg',
    status: 'Pending',
    value: 95.0,
  },
]
export default ordersList
